// NOTE: this file is generated by autobuild.rb
// degree of parallelism
// PAR_PRN  should be a power of 2, up to 32 (1, 2, 4, 8, 16, 32)
// PAR_FREQ should be a power of 5, up to 25 (1, 5, 25)
// PAR_CODE should be a divisor of 2046 (1, 2, 3, 6, 11, 22, 31, 33, ...)

#define PAR_PRN  1
#define PAR_FREQ 1
#define PAR_CODE 1
