########################################################################
# Auto build script for Vitis HLS 2022.04.14 Naoki F., AIT
########################################################################
require 'FileUtils'
require 'rubygems'

HLS_DIR      = 'C:\Xilinx\Vitis_HLS\2022.1'
PROJ_NAME    = 'hls_proj'
SOLUTION     = 'solution1'
TOP_FUNCTION = 'search'
BASE_DIR     = 'C:\Doc\x\research\GPS\gpsacq\gpsacq_hls_triple'
PROJ_DIR     = BASE_DIR + "\\" + PROJ_NAME
SOLUTION_DIR = PROJ_DIR + "\\" + SOLUTION
CSIM_LOG     = SOLUTION_DIR + '\csim\report' + "\\" + TOP_FUNCTION + '_csim.log'
REPORT_DIR   = SOLUTION_DIR + '\syn\report'
SYNTH_REPORT = SOLUTION_DIR + '\impl\verilog\project.runs\bd_0_hls_inst_0_synth_1' +
               '\bd_0_hls_inst_0_utilization_synth.rpt'
EXP_REPORT   = SOLUTION_DIR + '\impl\report\verilog\export_syn.rpt'
IP_FILE      = SOLUTION_DIR + '\impl\export.zip'

HEADER_FILE  = BASE_DIR + '\params.hpp'
LOG_FILE     = 'vitis_hls.log'

newpath = HLS_DIR + '\bin;' + ENV['PATH'];
newenv = {'PATH' => newpath, 'PROJECT_NAME' => PROJ_NAME,
          'PROJECT_BASE' => BASE_DIR.sub("\\", "/"), 'SOLUTION_NAME' => SOLUTION,
          'AUTOESL_HOME' => HLS_DIR, 'VIVADO_HLS_HOME' => HLS_DIR}

########################################################################
# options to be evaluated
PAR_PRN = [1, 2, 4, 8, 16, 32]
PAR_FREQ = [1, 5, 25]
PAR_CODE = [1, 2, 3, 6, 11, 22, 31, 33, 62, 66, 93, 186, 341, 682, 1023]
#PAR_PRN = [1]
#PAR_FREQ = [1]
#PAR_CODE = [1]

########################################################################
# main loop

resource_over = []
PAR_PRN.product(PAR_FREQ, PAR_CODE).each do |prn, freq, code|
  next if resource_over.include?([prn, freq])
  puts "## build: PRN %d, FREQ %d, CODE %d" % [prn, freq, code]
  puts
  sleep 1
  
  # make HEADER_FILE
  open(HEADER_FILE, 'w') do |file|
    file.puts "// NOTE: this file is generated by autobuild.rb"
    file.puts "// degree of parallelism"
    file.puts "// PAR_PRN  should be a power of 2, up to 32 (1, 2, 4, 8, 16, 32)"
    file.puts "// PAR_FREQ should be a power of 5, up to 25 (1, 5, 25)"
    file.puts "// PAR_CODE should be a divisor of 2046 (1, 2, 3, 6, 11, 22, 31, 33, ...)"
    file.puts
    file.puts "#define PAR_PRN  %d" % prn
    file.puts "#define PAR_FREQ %d" % freq
    file.puts "#define PAR_CODE %d" % code 
  end

  # run Vitis HLS
  IO.popen([newenv, HLS_DIR + '\bin\vitis_hls.bat',
           '-f', 'build.tcl']) do |io|
    while line = io.gets
      if line =~ /Finished/
        puts "%2d|%2d|%4d|%s" % [prn, freq, code, line.chomp]
      end
    end
  end
  if ! $?.success?
    puts "!! failed to build the core (with status %d). stop." % $?
    exit 1
  end

  # copy relavant file
  logdir = 'log\prn%d_freq%d_code%d' % [prn, freq, code]
  FileUtils.rm_rf logdir
  FileUtils.mkdir logdir
  FileUtils.mv   LOG_FILE    , logdir + '\hls_log.txt'
  # FileUtils.cp   CSIM_LOG    , logdir + '\csim_log.txt'
  FileUtils.cp_r REPORT_DIR  , logdir
  FileUtils.cp   SYNTH_REPORT, logdir + '\synth_rep.txt'
  FileUtils.cp   EXP_REPORT  , logdir + '\export_rep.txt'
  FileUtils.cp   IP_FILE     , logdir + '\export.zip'

  # detect resource over
  lut = ff = 0
  open(logdir + '/synth_rep.txt', 'r') do |file|
    while line = file.gets
      if line =~ /Slice LUTs[\* \|]+([0-9]+)/
        lut = $1.to_i
      elsif line =~ /Slice Registers[ \|]+([0-9]+)/
        ff = $1.to_i
      end
    end
  end
  puts "%2d|%2d|%4d| ## LUT = %d, FF = %d" % [prn, freq, code, lut, ff]
  resource_over << [prn, freq] if lut >= 50000 || ff >= 100000
end

########################################################################