########################################################################
# Auto build script for Vitis HLS (New Backend) 2026.06.14 Naoki F., AIT
# If you've installed Vivado 2023.1 or older, or you want to use the old
# backend in Vitis HLS 2023.2 or 2024.1, use autobuild_hls.rb instead.
########################################################################
require 'FileUtils'
require 'rubygems'

VITIS_DIR    = 'C:\Xilinx\Vitis\2024.1'
HLS_DIR      = 'C:\Xilinx\Vitis_HLS\2024.1'
COMP_NAME    = 'gpsacq'
TOP_FUNCTION = 'search'
IP_VLNV      = 'xilinx.com:hls:search:1.0'
SOURCE_DIR   = 'C:\path\where\this\repository\was\cloned'
BASE_DIR     = 'C:\path\to\your\vitis\workspace'
COMP_DIR     = BASE_DIR + "\\" + COMP_NAME
FUNC_DIR     = COMP_DIR + "\\" + TOP_FUNCTION
CSIM_LOG     = FUNC_DIR + '\logs\hls_run_csim.log'
REPORT_DIR   = FUNC_DIR + '\hls\syn\report'
SYNTH_REPORT = FUNC_DIR + '\hls\impl\verilog\project.runs\bd_0_hls_inst_0_synth_1' +
               '\bd_0_hls_inst_0_utilization_synth.rpt'
EXP_REPORT   = FUNC_DIR + '\hls\impl\report\verilog\export_syn.rpt'
IP_FILE      = FUNC_DIR + '\hls\impl\ip' + "\\" + IP_VLNV.gsub(/[\.:]/, '_') + '.zip'
HEADER_FILE  = SOURCEE_DIR + '\params.hpp'

newpath = VITIS_DIR + '\bin;' + ENV['PATH']
newpath = HLS_DIR + '\bin;' + newpath       if VITIS_DIR != HLS_DIR
newenv = {'PATH' => newpath, 'XILINX_VITIS' => HLS_DIR, 'XILINX_HLS' => HLS_DIR}

########################################################################
# options to be evaluated
PAR_PRN = [1, 2, 4, 8, 16, 32]
PAR_FREQ = [1, 5, 25]
PAR_CODE = [1, 2, 3, 6, 11, 22, 31, 33, 62, 66, 93, 186, 341, 682, 1023]
#PAR_PRN = [1]
#PAR_FREQ = [1]
#PAR_CODE = [1]

def run_hls (hls_arg, hls_logs, newenv, prn, freq, code)
  args = [newenv]
  args << VITIS_DIR + '\bin\vitis-run.bat'   if hls_arg != '--csynth'
  args += [VITIS_DIR + '\bin\v++.bat', '-c'] if hls_arg == '--csynth'
  args << VITIS_DIR + '\bin\v++.bat'         if hls_arg == '--csynth'
  args += ['--mode', 'hls',
           '--work_dir', COMP_DIR,
           '--config', COMP_DIR + '\hls_config.cfg']
  args << hls_arg                            if hls_arg != '--csynth'

  IO.popen(args) do |io|
    while line = io.gets
      hls_logs << line
      if line =~ /Finished/
        puts "%2d|%2d|%4d|%s" % [prn, freq, code, line.chomp]
      end
    end
  end
  if ! $?.success?
    puts "!! failed to build the core (with status %d). stop." % $?
    exit 1
  end
end

########################################################################
# main loop

resource_over = []
PAR_PRN.product(PAR_FREQ, PAR_CODE).each do |prn, freq, code|
  next if resource_over.include?([prn, freq])
  puts "## build: PRN %d, FREQ %d, CODE %d" % [prn, freq, code]
  puts
  sleep 1
  
  # make HEADER_FILE
  open(HEADER_FILE, 'w') do |file|
    file.puts "// NOTE: this file is generated by autobuild.rb"
    file.puts "// degree of parallelism"
    file.puts "// PAR_PRN  should be a power of 2, up to 32 (1, 2, 4, 8, 16, 32)"
    file.puts "// PAR_FREQ should be a power of 5, up to 25 (1, 5, 25)"
    file.puts "// PAR_CODE should be a divisor of 2046 (1, 2, 3, 6, 11, 22, 31, 33, ...)"
    file.puts
    file.puts "#define PAR_PRN  %d" % prn
    file.puts "#define PAR_FREQ %d" % freq
    file.puts "#define PAR_CODE %d" % code 
  end

  # run Vitis HLS
  hls_logs = ""
  # run_hls('--csim', hls_logs, newenv, prn, freq, code)
  run_hls('--csynth', hls_logs, newenv, prn, freq, code) # --csynth is pseudo-command for calling v++
  run_hls('--impl', hls_logs, newenv, prn, freq, code)


  # copy relavant file
  logdir = 'log\prn%d_freq%d_code%d' % [prn, freq, code]
  FileUtils.rm_rf logdir
  FileUtils.mkdir logdir
  open(logdir + '\hls_log.txt', 'w'){|x| x.write(hls_logs) }
  # FileUtils.cp   CSIM_LOG    , logdir + '\csim_log.txt'
  FileUtils.cp_r REPORT_DIR  , logdir
  FileUtils.cp   SYNTH_REPORT, logdir + '\synth_rep.txt'
  FileUtils.cp   EXP_REPORT  , logdir + '\export_rep.txt'
  FileUtils.cp   IP_FILE     , logdir + '\export.zip'

  # detect resource over
  lut = ff = 0
  open(logdir + '/synth_rep.txt', 'r') do |file|
    while line = file.gets
      if line =~ /Slice LUTs[\* \|]+([0-9]+)/
        lut = $1.to_i
      elsif line =~ /Slice Registers[ \|]+([0-9]+)/
        ff = $1.to_i
      end
    end
  end
  puts "%2d|%2d|%4d| ## LUT = %d, FF = %d" % [prn, freq, code, lut, ff]
  resource_over << [prn, freq] if lut >= 50000 || ff >= 100000
end

########################################################################